package tn.mechatitans.forms;

public enum subDomainType {
    COMPUTER_SCIENCE,MECHANICAL_ENGINEERING,CHEMICAL_ENGINEERING,CIVIL_ENGINEERING,ELECTRICAL_ENGINEERING,
    MARKETING,ENTREPRENEURSHIP,ACCOUNTING,
    ARTS,POIITICS,HISTORY,
    LANGUAGES,LAW,PHILOSOPHY,
    MEDICAL_STUDIES,PHARMACY,
    PHYSICS,MATHS,ASTRONOMY,
    SPORTS
}
